"""auth: user_profiles + role_page_permissions

Revision ID: 78d90d5310ad
Revises: a1afe2a8d505
Create Date: 2026-05-30 00:46:39.093747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d90d5310ad'
down_revision: Union[str, None] = 'a1afe2a8d505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'editor_chief', 'editor_a', 'editor_b', 'viewer', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=True)
    op.create_table('role_page_permissions',
    sa.Column('role', sa.Enum('admin', 'editor_chief', 'editor_a', 'editor_b', 'viewer', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role', 'page_id')
    )
    op.create_index(op.f('ix_role_page_permissions_page_id'), 'role_page_permissions', ['page_id'], unique=False)
    op.create_index(op.f('ix_content_blocks_lineage_id'), 'content_blocks', ['lineage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_blocks_lineage_id'), table_name='content_blocks')
    op.drop_index(op.f('ix_role_page_permissions_page_id'), table_name='role_page_permissions')
    op.drop_table('role_page_permissions')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
